### ISSUE TITLE
Handle non supported project types

### ISSUE THREAD

**Issue by vansickle** [VHQLabs/TargetFrameworkMigrator#10]
From VS gallery:

Unfortunately, when the extension finds a project type that doesn't specify a target framework it crashes with the following message "Object reference not set [...]". Unloading the project from the solution solves the issue, but it would be nice if the extension simply skipped these projects (they could be grayed in the grid or simply not listed). It's easy to reproduce with a SHFB project (https://shfb.codeplex.com/).

**Comment by vansickle** [comment]
Example from VS Gallery: "When your solutions contains a Sandcastle Project (Extension 
Sandcastle Help File Builder -> http://shfb.codeplex.com/) then it crashes with "Object reference not set to an instance of an object". Please fix this."

**Comment by stecydube** [comment]
Yes, please fix!
