### ISSUE TITLE
Add .net 4.6 support

### ISSUE THREAD

**Issue by fallenidol** [VHQLabs/TargetFrameworkMigrator#16]
Would be great to have .net 4.6 support. 

I managed to get around it for now by editing the Frameworks.xml file though.

**Comment by mereolog** [comment]
Would you mind sharing the secret?
That is, what change did you make?

**Comment by fallenidol** [comment]
I don't have it front of me unfortunately. But if you find the folder in AppData where this plugin keeps its files you will find a file called Frameworks.xml. In this file is a list of frameworks and I just added 4.6 to it and it worked ok for me.

**Comment by MartinPo** [comment]
Hi,
      
      on github are the sources with the 4.6 support.
      Didn´t had the time to test it on several platforms and therefor
      didn´t published it.
      
      If you like to support the testing process, please Email me and
      write your VS Edition.
      
      thanks in advance
      Martin
      
      Am 28.08.2015 um 11:52 schrieb Paul Mcilreavy:
    
    
      I don't have it front of me unfortunately. But if you find the
        folder in AppData where this plugin keeps its files you will
        find a file called Frameworks.xml. In this file is a list of
        frameworks and I just added 4.6 to it and it worked ok for me.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mereolog** [comment]
Yes, I am interested in supporting the testing process.

 

I run VS Enterprise 2015 version 14.0.23107.0 D14REL

 

 

Regards,

 

 

Pawel  Garbacz
