### ISSUE TITLE
Update from 1.5 to 1.6 in Visual Studio 2013 results in failure to load

### ISSUE THREAD

**Issue by chiefengineer** [VHQLabs/TargetFrameworkMigrator#19]
![errorinvisualstudio2013](https://cloud.githubusercontent.com/assets/3935857/10110236/d195fd48-6380-11e5-9701-1d3db71f1217.png)

The only change to this instance of VS (it runs in a VMWare session and has worked in it's older incarnation (v1.5) for the better part of a year).

**Comment by dougwebb** [comment]
Commit 5176ca00efd290692b8b9ee7145a6c907cf6dc7d changed MinimumVisualStudioVersion from 12 to 14, which would cause it to fail to load in VS2013.

**Comment by wpoPR** [comment]
any news?

**Comment by dougwebb** [comment]
I had to downgrade to 1.5, using a download that a colleague of mine had from before the 1.6 release.

**Comment by vansickle** [comment]
MinimumVisualStudioVersion is project version, not cause of failed load - so not so easy to fix, but done.
