### ISSUE TITLE
[Query] Can we run this on multiple sln files? 

### ISSUE THREAD

**Issue by ip28** [VHQLabs/TargetFrameworkMigrator#23]
What if I want to migrate all the solutions in a certain folder, is there any option to do that?

**Comment by vansickle** [comment]
As I understand, you can't open multiple Solutions in Visual Studio hence can't use TFM to migrate multiple solutions at once

You can:

- Import all projects in one solution and update projects
- (Not sure it's easy or possible) Update TFM code to support run from command and run devenv.exe from commandline https://msdn.microsoft.com/en-us/library/ms228759.aspx
- (Not sure it's easy or possible) Automate VS http://www.mztools.com/articles/2005/mz2005005.aspx
