### ISSUE TITLE
Multiple Solution Support?

### ISSUE THREAD

**Issue by Eddie-Hartman** [VHQLabs/TargetFrameworkMigrator#26]
I'm in charge of migrating the .net framework at the company I work at and we use ~30 solutions and have multiple products that each will individually need migrated. I have the list of solutions. Is there any way that I can tell the tool to migrate all of them at once instead of doing each one individually?

**Comment by vansickle** [comment]
See my answer for #23 - that's my thoughts how you can try to use TFM in your case. Also, may be in your case it's easier to write custom tool/script which updates xml in .*proj files
