### ISSUE TITLE
VS2017 support?

### ISSUE THREAD

**Issue by Leon99** [VHQLabs/TargetFrameworkMigrator#28]
Pretty please

**Comment by Profi-Concept** [comment]
I've made some crude steps to support Visual Studio 2017 (see Pullrequest #29 ). It isn't ready for release but worked on a 50 plus projects solution in VS2017.

**Comment by vansickle** [comment]
@Profi-Concept I've seen your pull request, I'll test and release it as soon as I can.

**Comment by niemyjski** [comment]
@vansickle were you able to look at this?

**Comment by vansickle** [comment]
VS 2017 support is merged
