### ISSUE TITLE
Target Framework Extension fails to load if your solution has Sandcastle Projects 

### ISSUE THREAD

**Issue by pateljeel** [VHQLabs/TargetFrameworkMigrator#34]
If your solution contains a Sandcastle project, the extension will fail to open. You will get an Object reference not set to an instance of an object message. 

You will have to manually migrate the Sandcastle projects.

**Comment by Draghi** [comment]
+1 Ran into this issue as well

**Comment by vansickle** [comment]
duplicates #10
